### ISSUE TITLE
It breaks the dot command

### ISSUE THREAD

**Issue by lourenci** [tversteeg/registers.nvim#19]
After pasting from a register, the dot command does not work as expected.

I made a video to show the problem, I hope you can get the problem with it.

https://user-images.githubusercontent.com/2339362/119131735-39638a80-ba10-11eb-847b-ac6614ea3b27.mov

Thank you.

EDIT: typo in the video. The result of the dot command is expected to be `{ foo`, but with this plugin: `{`.

**Comment by habamax** [comment]
https://github.com/tversteeg/registers.nvim/blob/bb6e6f83f4779038609b7ab85514f3b661d74f67/plugin/registers.vim#L21

Why do you use `<C-O>` there? It will change the mode but you don't want this

**Comment by tversteeg** [comment]
Thanks @habamax, but with this change it still doesn't work.

**Comment by habamax** [comment]
works for me with this sample in vim:

![Uploading vim-cmd-dot-reg.gif…]()

**Comment by habamax** [comment]
Are we talking about dot register or dot command 🤣

**Comment by tversteeg** [comment]
The dot command.. Is that different from the dot register?

**Comment by habamax** [comment]
> The dot command.. Is that different from the dot register?

Sure. Dot command repeats last change and with `vim-repeat` of tpope it might repeat a complex changes too.

Dot register has last inserted text:

`dd` -- with dot I will repeat `dd` command but dot register would be what it has since last text insertion.

1. Type `ihello<ESC>`  -- your dot register has `hello`
2. goto `l` and press `dw` -- your dot register still has `hello` but dot command would repeat `dw` next time you press it.

**Comment by tversteeg** [comment]
In that case I understand the situation, I made the assumption that they are the same. But now that I think of it that's not a very smart assumption to make...

**Comment by QiBaobin** [comment]
#22
